### ISSUE TITLE
Enroll in GH larger runners to access KVM for NixOS tests

### ISSUE THREAD

**Issue by elpdt852** [pdtpartners/nix-snapshotter#36]
Looks like KVM is not allowed on standard runners and we'll have to upgrade to [larger runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners) to run NixOS tests on GH actions. If we are able to get it, then here's how to enable it.

See this [example repo](https://github.com/skatolo/gh-actions-nixos-tests/blob/main/.github/workflows/nixos-tests.yml), but it's using a third party GH runner

- [ ] Enable KVM group perms in the GH workflow. [See GH blog](https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/)
```yaml
      - name: Enable KVM group perms
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm
```
- [ ] Configure `cachix/install-nix-action` to enable `kvm`:
```yaml
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
```
- [ ] Possibly need to chmod `/dev/kvm`:
```yaml
          sudo chmod o+rw /dev/kvm
          nix flake check
```
